"""Low-level process, protocol and transport client for kompas_bridge."""

from kompas_bridge_transport._windows.named_pipe import DEFAULT_PIPE_NAME, NamedPipeClient
from kompas_bridge_transport.client import BridgeClient, BridgeClientSettings
from kompas_bridge_transport.errors import (
    BridgeConnectionError,
    BridgeError,
    BridgeInternalError,
    BridgeProcessError,
    BridgeProtocolError,
    BridgeRemoteError,
    BridgeTimeoutError,
    InvalidParamsError,
    InvalidRequestError,
    KompasApiError,
    KompasNotRunningError,
    NoActiveDocumentError,
    ObjectInvalidatedError,
    ObjectNotFoundError,
    UnknownMethodError,
    UnsupportedProtocolVersionError,
)
from kompas_bridge_transport.handles import (
    BridgeHandle,
    BodyHandle,
    DocumentHandle,
    FeatureHandle,
    FaceHandle,
    EdgeHandle,
    PartHandle,
    SketchHandle,
)
from kompas_bridge_transport.process import BridgeProcessManager

__all__ = [
    "DEFAULT_PIPE_NAME",
    "BridgeClient",
    "BridgeClientSettings",
    "BridgeConnectionError",
    "BridgeError",
    "BridgeHandle",
    "BodyHandle",
    "BridgeInternalError",
    "BridgeProcessError",
    "BridgeProcessManager",
    "BridgeProtocolError",
    "BridgeRemoteError",
    "BridgeTimeoutError",
    "DocumentHandle",
    "FeatureHandle",
    "FaceHandle",
    "EdgeHandle",
    "InvalidParamsError",
    "InvalidRequestError",
    "KompasApiError",
    "KompasNotRunningError",
    "NamedPipeClient",
    "NoActiveDocumentError",
    "ObjectInvalidatedError",
    "ObjectNotFoundError",
    "PartHandle",
    "SketchHandle",
    "UnknownMethodError",
    "UnsupportedProtocolVersionError",
]
