"""High-level Python API for KOMPAS-3D automation."""

from kompas_core.application import ApplicationStatus, KompasApplication, KompasVersion
from kompas_core.common.errors import (
    CoreBridgeError,
    CoreConnectionError,
    CoreError,
    CoreNoActiveDocumentError,
    CoreObjectInvalidatedError,
    CoreObjectNotFoundError,
    CoreProcessError,
    CoreProtocolError,
    CoreRemoteError,
    CoreSelectionAmbiguousError,
    CoreSelectionError,
    CoreSelectionNotFoundError,
    CoreSessionClosedError,
    CoreTimeoutError,
)
from kompas_core.connection import connect
from kompas_core.documents import Document, DocumentState
from kompas_core.features import (
    BooleanOperation,
    ExtrusionDirection,
    ExtrusionParameters,
    Feature,
    FeatureCollection,
    FeatureInfo,
    FeatureKind,
    FeatureState,
)
from kompas_core.objects import KompasObject, ObjectInfo
from kompas_core.measurements import AngleMeasurement, DistanceMeasurement, Measurements
from kompas_core.geometry import (
    Body,
    BodyCollection,
    BodyInfo,
    BoundingBox3D,
    Face,
    FaceCollection,
    FaceGeometry,
    MassProperties,
    MomentsOfInertia,
    Point3D,
    SurfaceType,
)
from kompas_core.parts import Part
from kompas_core.recipes import create_cube
from kompas_core.sketches import Circle, LineSegment, Point2D, Sketch, SketchPlane, SketchState

__all__ = [
    "ApplicationStatus",
    "AngleMeasurement",
    "BooleanOperation",
    "Body",
    "BodyCollection",
    "BodyInfo",
    "BoundingBox3D",
    "Circle",
    "CoreBridgeError",
    "CoreConnectionError",
    "CoreError",
    "CoreNoActiveDocumentError",
    "CoreObjectInvalidatedError",
    "CoreObjectNotFoundError",
    "CoreProcessError",
    "CoreProtocolError",
    "CoreRemoteError",
    "CoreSelectionAmbiguousError",
    "CoreSelectionError",
    "CoreSelectionNotFoundError",
    "CoreSessionClosedError",
    "CoreTimeoutError",
    "Document",
    "DocumentState",
    "DistanceMeasurement",
    "ExtrusionDirection",
    "ExtrusionParameters",
    "Feature",
    "FeatureCollection",
    "FeatureInfo",
    "FeatureKind",
    "FeatureState",
    "Face",
    "FaceCollection",
    "FaceGeometry",
    "KompasObject",
    "KompasApplication",
    "KompasVersion",
    "LineSegment",
    "MassProperties",
    "MomentsOfInertia",
    "Measurements",
    "ObjectInfo",
    "Part",
    "Point2D",
    "Point3D",
    "Sketch",
    "SketchPlane",
    "SketchState",
    "SurfaceType",
    "connect",
    "create_cube",
]
